### ISSUE TITLE
Exit window trigger assertion failed

### ISSUE THREAD

**Issue by DreamMaoMao** [r0-zero/picom#31]
### Platform
arch amd64

### GPU, drivers, and screen setup
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz
screen setup: one monitor
glxinfo -B:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon Vega 8 Graphics (raven, LLVM 16.0.6, DRM 3.54, 6.5.7-arch1-1) (0x15d8)
    Version: 23.2.1
    Accelerated: yes
    Video memory: 2048MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 1741 MB, largest block: 1741 MB
    VBO free aux. memory - total: 2878 MB, largest block: 2878 MB
    Texture free memory - total: 1741 MB, largest block: 1741 MB
    Texture free aux. memory - total: 2878 MB, largest block: 2878 MB
    Renderbuffer free memory - total: 1741 MB, largest block: 1741 MB
    Renderbuffer free aux. memory - total: 2878 MB, largest block: 2878 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 4985 MB
    Currently available dedicated video memory: 1741 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon Vega 8 Graphics (raven, LLVM 16.0.6, DRM 3.54, 6.5.7-arch1-1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.2.1-arch1.2
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.2.1-arch1.2
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.2.1-arch1.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

```

### Environment
dwm

### picom version
vgit-21728

<details>
<summary>Diagnostics</summary>

```
**Version:** vgit-21728

### Extensions:

* Shape: Yes
* RandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/wrq/.config/picom.conf

### Drivers (inaccurate):

modesetting

### Backend: glx

* Driver vendors:
 * GLX: Mesa Project and SGI
 * GL: AMD
* GL renderer: AMD Radeon Vega 8 Graphics (raven, LLVM 16.0.6, DRM 3.54, 6.5.7-arch1-1)
* Accelerated: 1

### Backend: egl

* Driver vendors:
 * EGL: Mesa Project
 * EGL driver: radeonsi
 * GL: AMD
* GL renderer: AMD Radeon Vega 8 Graphics (raven, LLVM 16.0.6, DRM 3.54, 6.5.7-arch1-1)


```
</details>

### Configuration:
<details>
    <summary>Configuration file</summary>

```
// Paste your configuration here
# 基础设置

#log-level = "debug"
#log-level = "warn";

# 设置日志文件。
# 如果 *--log-file* 从未指定，日志将被写入标准错误。
# 否则，日志将写入给定文件，尽管一些早期的
# 日志可能仍会写入标准错误。
# 从配置文件中设置此选项时，建议使用绝对路径。
#
#log-file = "/var/log/picom.log";

# 显示所有 X 错误（用于调试）
#show-all-xerrors = false;

# 将进程 ID 写入文件。
# write-pid-path = "/path/to/your/log/file"



backend = "glx";
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-client-opacity = true;
unredir-if-possible = true;
vsync = true;
dbe = false;
detect-transient = true;
detect-client-leader = true;
invert-color-include = [ ];
glx-copy-from-front = false;

# 圆角
corner-radius = 15.0;
round-borders = 5;
rounded-corners-exclude = [
    "class_g = 'baidu-qimpanel'",
    "class_g = 'fcitx-qimpanel'",
    "class_g = 'Polybar'",
    "class_g = 'Dragon'",
    "class_g *= 'fcitx'"
];

# 阴影
shadow = false;
detect-rounded-corners = false;
shadow-radius = 4;
shadow-offset-x = 0;
shadow-offset-y = 0;
shadow-opacity = 0.25;
shadow-ignore-shaped = false;
shadow-exclude = [
	"_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
	"_GTK_FRAME_EXTENTS@:c",
	"override_redirect = 1 && !WM_CLASS@:s",
    "name = 'Notification'",
    "class_g ?= 'Dmenu'",
    "class_g *= 'dwm'",
    "class_g *= 'smplayer'",
    "class_g = 'baidu-qimpanel'",
    "class_g = 'fcitx-qimpanel'",
    "class_g *= 'Wine'",
    "class_g *= 'fcitx'",
    "name = 'Dunst'",
    "class_g *= 'float'"
];

# 透明
active-opacity = 0.95;

opacity-rule = [
    "100:_NET_WM_STATE@:32a *= '_NET_WM_STATE_STICKY'", # 画中画
    "100:_NET_WM_STATE@:32a *= '_NET_WM_STATE_FULLSCREEN' && WM_CLASS@:s *= 'Google-chrome-unstable'", # 全屏 chrome 窗口
    "100:WM_NAME@:s = '画中画'",
    "100:WM_CLASS@:s *= 'vncviewer'",
    "100:class_g = 'mpv'",
    "100:class_g = 'baidu-qimpanel'",
    "100:class_g = 'sogoupinyin-service'",
    "100:class_g = 'fcitx-qimpanel'",
    "99:class_g = 'smplayer'",
    "100:class_g = 'obs'",
    "100:class_g = 'Gimp'",
    "100:class_g = 'Rofi'",
    "100:class_g = 'Dragon'",
    "10:class_g = 'Polybar'",
    "90:WM_CLASS@:s *= 'Google-chrome-unstable' && !focused",
    "80:!focused"
];

# 淡入淡出
fading = true;
fade-delta = 2;
fade-in-step = 0.01;
fade-out-step = 0.01;
fade-exclude = [
    "class_g *= 'fcitx'",
    "WM_CLASS@:s *= 'screenkey'"
];

# 动画
animations = true;
animation-window-mass = 0.5;
animation-dampening = 16;
animation-stiffness-in-tag = 150;
animation-stiffness-tag-change = 150;
animation-for-open-window = "zoom";
# animation-for-unmap-window = "slide-up";
animation-for-unmap-window = "squeeze";
enable-fading-next-tag = true;
#animation-for-next-tag = "slide-left";
animation-exclude = [
    "class_g = 'fcitx'",
    "class_g = 'flameshot'",
    "class_g = 'baidu-qimpanel'",
    "class_g = 'Dunst'",
    "class_g = 'fcitx-qimpanel'",
    "class_g = 'sogoupinyin-service'",
    "WM_CLASS@:s *= 'screenkey'"
];

# 模糊
#blur-background=false;
blur-method = "dual_kawase";
#blur-method = "none";
blur-strength = 3;
blur-kern = "3x3box";
blur-background-exclude = [
    # "class_g *= 'dwm'",
	"window_type = 'dock'",
	"window_type = 'desktop'",
	"_GTK_FRAME_EXTENTS@:c",
    "name *? = 'Sunflower'",
    "class_g *= 'wemeetapp'",
    "class_g *= 'smplayer'",
    "class_g *= 'konsole'",
    "class_g *= 'terminal'",
    "class_g *= 'Dragon'",
    "class_g *= 'Google-chrome-unstable'",
    "class_g = 'baidu-qimpanel'",
    "class_g = 'fcitx-qimpanel'",
    "class_g *= 'Gnome-terminal'",
    "class_g = 'sogoupinyin-service'",
    "class_g *= 'fcitx'",
    "class_g *= 'Rofi'"
];

# 针对窗口类型的设置
wintypes :
{
  tooltip: { fade = true; shadow = false; opacity = 0.85; focus = true; };
  fullscreen: { fade = true; shadow = false; focus = true; opacity = 0.93; };
};

```
</details>

### Steps of reproduction

1.exit a window

### Expected behavior
picom crashes after exiting a window

### Stack trace
coredump:

```
#0  0x00007fb527fb683c in ?? () from /usr/lib/libc.so.6
#1  0x00007fb527f66668 in raise () from /usr/lib/libc.so.6
#2  0x00007fb527f4e4b8 in abort () from /usr/lib/libc.so.6
#3  0x00007fb527f4e3dc in ?? () from /usr/lib/libc.so.6
#4  0x00007fb527f5ed26 in __assert_fail () from /usr/lib/libc.so.6
#5  0x0000556753c00782 in win_on_win_size_change (ps=0x5567542f4eb0, w=0x5567546293b0) at ../src/win.c:1532
#6  0x0000556753bf11d6 in paint_preprocess (ps=0x5567542f4eb0, fade_running=0x7fff7e7eb7ac, 
    animation_running=0x7fff7e7eb7ad) at ../src/picom.c:949
#7  0x0000556753bf49a4 in draw_callback_impl (loop=0x7fb528549060, ps=0x5567542f4eb0, revents=256) at ../src/picom.c:1925
#8  0x0000556753bf4e21 in draw_callback (loop=0x7fb528549060, w=0x5567542f4fc0, revents=256) at ../src/picom.c:1996
#9  0x00007fb52853e0cb in ev_invoke_pending () from /usr/lib/libev.so.4
#10 0x00007fb528541d10 in ev_run () from /usr/lib/libev.so.4
#11 0x0000556753bfa288 in session_run (ps=0x5567542f4eb0) at ../src/picom.c:2941
#12 0x0000556753bfa5e3 in main (argc=3, argv=0x7fff7e7ebaa8) at ../src/picom.c:3046

```

picom log:
```
picom: ../src/win.c:1532：win_on_win_size_change: assume ‘w->state != WSTATE_UNMAPPED && w->state != WSTATE_DESTROYING && w->state != WSTATE_UNMAPPING’ fail。
```

**Comment by r0-zero** [comment]
This does not happen to me on dwm (pdwm), could you try this again with the latest version?

**Comment by DreamMaoMao** [comment]
the issue has disappeared in  latest version
